attach terms of service pdf fixes AB#754
AMPnet/mail-service pull request #40
Opened 2021-01-22 14:35 UTC by josipkoncurat

@Eugen Define new email text.

2021-01-22 14:37 UTC, eugen commented
@josipkoncurat hey, probably wrong Eugen :)

2021-01-22 14:39 UTC, josipkoncurat commented
@eugen yep, wrong one :)

2021-01-22 14:39 UTC, josipkoncurat commented
@githinho please define mail text.

2021-01-22 14:52 UTC, githinho commented
> @githinho please define mail text.

@filipdujmusic

2021-01-25 08:13 UTC, githinho requested changes

2021-01-25 08:13 UTC, githinho commented on src/main/kotlin/com/ampnet/mailservice/service/impl/FileServiceImpl.kt
> +class FileServiceImpl(private val restTemplate: RestTemplate) : FileService {
It would be nice to store downloaded files because most of the time the same document will be used.

2021-01-25 08:13 UTC, githinho commented on src/main/kotlin/com/ampnet/mailservice/service/impl/FileServiceImpl.kt
> +
Throws `ResourceNotFoundException`

2021-01-25 08:13 UTC, githinho commented on src/main/kotlin/com/ampnet/mailservice/service/impl/mail/AbstractMail.kt
> +                val helper = if (this::attachment.isInitialized) {
Set `attachment` as nullable to simplify code.

2021-01-25 08:13 UTC, githinho commented on src/test/kotlin/com/ampnet/mailservice/service/FileServiceTest.kt
> +
@Disabled("Not for automated testing")

2021-01-25 10:10 UTC, githinho commented on src/main/kotlin/com/ampnet/mailservice/service/impl/FileServiceImpl.kt
> +        }
```suggestion
        termsOfService[url]?.let { return it }
        try {
            val responseEntity = restTemplate.exchange<Resource>(url, HttpMethod.GET, HttpEntity.EMPTY)
            val inputStream = readInputStream(responseEntity, url)
            termsOfService[url] = inputStream
            return inputStream
        } catch (ex: RestClientException) {
            throw ResourceNotFoundException("Error while reading response from $url", ex)
        }
```

2021-01-25 11:05 UTC, githinho approved these changes

2021-01-25 11:05 UTC, merged